using PRN222.BLL.DTOs;

namespace PRN222.BLL.Services.Interfaces;

public interface ITestSetGeneratorService
{
    Task<int> GenerateFromDocumentsAsync(int courseId, int questionsPerChunk = 2, int maxChunks = 25);
    Task<int> GenerateFromDocumentsAsync(
        int courseId,
        int questionsPerChunk,
        int maxChunks,
        CancellationToken cancellationToken,
        ITestSetGenerationJobManager? jobManager = null);
    Task ClearAutoGeneratedAsync(int courseId);
    Task<TestSetStatsDto> GetStatsAsync(int courseId);
    Task<PagedResult<QAPairDto>> GetAutoGeneratedPreviewAsync(int courseId, int page = 1, int pageSize = 25);
}
