using FluentAssertions;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Moq;
using PRN222.BLL.Services;
using PRN222.BLL.Services.Interfaces;
using PRN222.DAL.Entities;
using PRN222.DAL.Entities.Enums;
using PRN222.DAL.Repositories.Interfaces;

namespace PRN222.Tests.Services;

public class TestSetGeneratorServiceTests
{
    private readonly Mock<IQAPairRepository> _qaPairRepositoryMock = new();
    private readonly Mock<IDocumentRepository> _documentRepositoryMock = new();
    private readonly Mock<IChunkRepository> _chunkRepositoryMock = new();
    private readonly Mock<ILlmService> _llmServiceMock = new();
    private readonly Mock<IUnitOfWork> _unitOfWorkMock = new();
    private readonly Mock<ILogger<TestSetGeneratorService>> _loggerMock = new();
    private readonly IConfiguration _configuration = new ConfigurationBuilder()
        .AddInMemoryCollection(new Dictionary<string, string?>
        {
            ["Gemini:RateLimit:ChunkDelayMs"] = "0",
            ["Gemini:RateLimit:RetryDelayMs"] = "0"
        })
        .Build();

    [Fact]
    public async Task GenerateFromDocumentsAsync_ShouldCreateQaPairsLinkedToSourceChunk()
    {
        var courseId = 1;
        var documents = new List<Document>
        {
            new() { Id = 7, CourseId = courseId, Status = DocumentStatus.Indexed }
        };
        var chunks = new List<DocumentChunk>
        {
            new()
            {
                Id = 11,
                DocumentId = 7,
                Content = new string('A', 160)
            }
        };

        _documentRepositoryMock.Setup(r => r.GetByCourseIdAsync(courseId))
            .ReturnsAsync(documents);
        _chunkRepositoryMock.Setup(r => r.GetChunksWithEmbeddingsByDocumentIdsAsync(It.Is<IList<int>>(ids => ids.SequenceEqual(new[] { 7 }))))
            .ReturnsAsync(chunks);
        _llmServiceMock.Setup(s => s.GenerateQAPairsAsync(chunks[0].Content, 2))
            .ReturnsAsync("""
                [
                  { "question": "Question 1?", "answer": "Answer 1" },
                  { "question": "Question 2?", "answer": "Answer 2" }
                ]
                """);

        var service = CreateService();

        var created = await service.GenerateFromDocumentsAsync(courseId, questionsPerChunk: 2, maxChunks: 1);

        created.Should().Be(2);
        _qaPairRepositoryMock.Verify(r => r.AddAsync(It.Is<QAPair>(qa =>
            qa.CourseId == courseId &&
            qa.DocumentChunkId == 11 &&
            qa.Question == "Question 1?" &&
            qa.Answer == "Answer 1" &&
            qa.RelevanceScore == 1.0)), Times.Once);
        _qaPairRepositoryMock.Verify(r => r.AddAsync(It.Is<QAPair>(qa =>
            qa.CourseId == courseId &&
            qa.DocumentChunkId == 11 &&
            qa.Question == "Question 2?" &&
            qa.Answer == "Answer 2")), Times.Once);
        _unitOfWorkMock.Verify(u => u.SaveChangesAsync(), Times.Once);
    }

    [Fact]
    public async Task GenerateFromDocumentsAsync_ShouldStopBeforeProcessingChunks_WhenCancellationRequested()
    {
        var courseId = 1;
        var documents = new List<Document>
        {
            new() { Id = 7, CourseId = courseId, Status = DocumentStatus.Indexed }
        };
        var chunks = new List<DocumentChunk>
        {
            new() { Id = 11, DocumentId = 7, Content = new string('A', 160) }
        };
        using var cts = new CancellationTokenSource();
        cts.Cancel();

        _documentRepositoryMock.Setup(r => r.GetByCourseIdAsync(courseId))
            .ReturnsAsync(documents);
        _chunkRepositoryMock.Setup(r => r.GetChunksWithEmbeddingsByDocumentIdsAsync(It.IsAny<IList<int>>()))
            .ReturnsAsync(chunks);

        var service = CreateService();

        var created = await service.GenerateFromDocumentsAsync(courseId, 2, 1, cts.Token);

        created.Should().Be(0);
        _llmServiceMock.Verify(s => s.GenerateQAPairsAsync(It.IsAny<string>(), It.IsAny<int>()), Times.Never);
        _qaPairRepositoryMock.Verify(r => r.AddAsync(It.IsAny<QAPair>()), Times.Never);
    }

    [Fact]
    public async Task GetAutoGeneratedPreviewAsync_ShouldReturnPagedResults()
    {
        var courseId = 1;
        var qaPairs = Enumerable.Range(1, 11)
            .Select(id => new QAPair
            {
                Id = id,
                CourseId = courseId,
                DocumentChunkId = 100 + id,
                Question = $"Question {id}?",
                Answer = $"Answer {id}",
                CreatedAt = DateTime.UtcNow
            })
            .ToList();

        _qaPairRepositoryMock.Setup(r => r.GetQueryable())
            .Returns(qaPairs.AsAsyncQueryable());

        var service = CreateService();

        var result = await service.GetAutoGeneratedPreviewAsync(courseId, page: 2, pageSize: 10);

        result.Page.Should().Be(2);
        result.PageSize.Should().Be(10);
        result.TotalItems.Should().Be(11);
        result.TotalPages.Should().Be(2);
        result.Items.Should().ContainSingle(item => item.Id == 1);
    }

    private TestSetGeneratorService CreateService()
    {
        return new TestSetGeneratorService(
            _qaPairRepositoryMock.Object,
            _documentRepositoryMock.Object,
            _chunkRepositoryMock.Object,
            _llmServiceMock.Object,
            _unitOfWorkMock.Object,
            _loggerMock.Object,
            _configuration);
    }
}
