namespace PRN222.DAL.Entities.Enums;

/// <summary>
/// Represents the role of a message in a chat conversation.
/// </summary>
public enum MessageRole
{
    /// <summary>Message sent by the user.</summary>
    User = 0,

    /// <summary>Message generated by the assistant/chatbot.</summary>
    Assistant = 1
}
