using FluentAssertions;
using CodeRunnerIndexModel = PRN222.Web.Pages.CodeRunner.IndexModel;
using EvaluationCompareModel = PRN222.Web.Pages.Evaluation.CompareModel;
using EvaluationIndexModel = PRN222.Web.Pages.Evaluation.IndexModel;
using EvaluationRunDetailModel = PRN222.Web.Pages.Evaluation.RunDetailModel;
using FinetuneDatasetModel = PRN222.Web.Pages.Finetune.DatasetModel;
using FinetuneIndexModel = PRN222.Web.Pages.Finetune.IndexModel;
using KnowledgeIndexModel = PRN222.Web.Pages.Knowledge.IndexModel;
using TestSetGeneratorIndexModel = PRN222.Web.Pages.TestSetGenerator.IndexModel;
using TestSetIndexModel = PRN222.Web.Pages.TestSet.IndexModel;

namespace PRN222.Tests.Web;

public class ModelOperationsRazorPagesTests
{
    [Theory]
    [InlineData("Evaluation", "Index.cshtml")]
    [InlineData("Evaluation", "RunDetail.cshtml")]
    [InlineData("Evaluation", "Compare.cshtml")]
    [InlineData("Finetune", "Index.cshtml")]
    [InlineData("Finetune", "Dataset.cshtml")]
    [InlineData("TestSetGenerator", "Index.cshtml")]
    [InlineData("Knowledge", "Index.cshtml")]
    [InlineData("CodeRunner", "Index.cshtml")]
    [InlineData("TestSet", "Index.cshtml")]
    public void ModelOperationPages_ShouldExist(params string[] pathSegments)
    {
        var root = FindRepositoryRoot();

        File.Exists(Path.Combine([root, "src", "PRN222.Web", "Pages", .. pathSegments]))
            .Should().BeTrue();
    }

    [Fact]
    public void EvaluationPages_ShouldExposeHandlers()
    {
        typeof(EvaluationIndexModel).GetMethod(nameof(EvaluationIndexModel.OnGetAsync)).Should().NotBeNull();
        typeof(EvaluationIndexModel).GetMethod(nameof(EvaluationIndexModel.OnGetRunStatusesAsync)).Should().NotBeNull();
        typeof(EvaluationIndexModel).GetMethod(nameof(EvaluationIndexModel.OnPostCreateRunAsync)).Should().NotBeNull();
        typeof(EvaluationRunDetailModel).GetMethod(nameof(EvaluationRunDetailModel.OnGetAsync)).Should().NotBeNull();
        typeof(EvaluationRunDetailModel).GetMethod(nameof(EvaluationRunDetailModel.OnGetExportCsvAsync)).Should().NotBeNull();
        typeof(EvaluationCompareModel).GetMethod(nameof(EvaluationCompareModel.OnGetAsync)).Should().NotBeNull();
    }

    [Fact]
    public void FinetuneAndTestSetPages_ShouldExposeHandlers()
    {
        typeof(FinetuneIndexModel).GetMethod(nameof(FinetuneIndexModel.OnGetAsync)).Should().NotBeNull();
        typeof(FinetuneDatasetModel).GetMethod(nameof(FinetuneDatasetModel.OnGetAsync)).Should().NotBeNull();
        typeof(FinetuneDatasetModel).GetMethod(nameof(FinetuneDatasetModel.OnPostGenerateAjaxAsync)).Should().NotBeNull();
        typeof(FinetuneDatasetModel).GetMethod(nameof(FinetuneDatasetModel.OnGetExportAsync)).Should().NotBeNull();
        typeof(TestSetGeneratorIndexModel).GetMethod(nameof(TestSetGeneratorIndexModel.OnGetAsync)).Should().NotBeNull();
        typeof(TestSetGeneratorIndexModel).GetMethod(nameof(TestSetGeneratorIndexModel.OnPostGenerateAsync)).Should().NotBeNull();
        typeof(TestSetGeneratorIndexModel).GetMethod(nameof(TestSetGeneratorIndexModel.OnPostStopAsync)).Should().NotBeNull();
        typeof(TestSetGeneratorIndexModel).GetMethod(nameof(TestSetGeneratorIndexModel.OnPostClearAutoGeneratedAsync)).Should().NotBeNull();
        typeof(TestSetGeneratorIndexModel).GetMethod(nameof(TestSetGeneratorIndexModel.OnGetStatsAsync)).Should().NotBeNull();
        typeof(TestSetGeneratorIndexModel).GetMethod(nameof(TestSetGeneratorIndexModel.OnGetJobStatusAsync)).Should().NotBeNull();
        typeof(TestSetGeneratorIndexModel).GetMethod(nameof(TestSetGeneratorIndexModel.OnGetPreviewAsync)).Should().NotBeNull();
        typeof(TestSetIndexModel).GetMethod(nameof(TestSetIndexModel.OnPostSeedAsync)).Should().NotBeNull();
        typeof(TestSetIndexModel).GetMethod(nameof(TestSetIndexModel.OnGetPreviewAsync)).Should().NotBeNull();
    }

    [Fact]
    public void KnowledgeAndCodeRunnerPages_ShouldExposeHandlers()
    {
        typeof(KnowledgeIndexModel).GetMethod(nameof(KnowledgeIndexModel.OnPostProposeAsync)).Should().NotBeNull();
        typeof(KnowledgeIndexModel).GetMethod(nameof(KnowledgeIndexModel.OnPostApproveAsync)).Should().NotBeNull();
        typeof(KnowledgeIndexModel).GetMethod(nameof(KnowledgeIndexModel.OnPostRejectAsync)).Should().NotBeNull();
        typeof(KnowledgeIndexModel).GetMethod(nameof(KnowledgeIndexModel.OnPostRollbackAsync)).Should().NotBeNull();
        typeof(CodeRunnerIndexModel).GetMethod(nameof(CodeRunnerIndexModel.OnPostExecuteAsync)).Should().NotBeNull();
    }

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null)
        {
            if (Directory.Exists(Path.Combine(directory.FullName, ".git"))
                || File.Exists(Path.Combine(directory.FullName, ".git")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new DirectoryNotFoundException("Could not locate the repository root.");
    }
}
