using FluentAssertions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Moq;
using PRN222.BLL.DTOs;
using PRN222.BLL.Services.Interfaces;
using PRN222.Web.Pages.TestSetGenerator;

namespace PRN222.Tests.Web;

public class TestSetGeneratorPageTests
{
  [Fact]
  public async Task IndexPage_ShouldSelectFirstCourse_WhenCourseIdIsMissing()
  {
    var generator = new Mock<ITestSetGeneratorService>();
    var jobs = new Mock<ITestSetGenerationJobManager>();
    var backgroundQueue = new Mock<IBackgroundTaskQueue>();
    var courses = new Mock<ICourseService>();
    var courseAccess = new Mock<ICourseAccessService>();
    var courseList = new[]
    {
        new CourseDto(7, "PRN222", "ASP.NET Core MVC", 3, DateTime.UtcNow),
        new CourseDto(9, "SWT301", "Software testing", 1, DateTime.UtcNow)
    };

    courses.Setup(s => s.GetAllCoursesAsync()).ReturnsAsync(courseList);
    generator.Setup(s => s.GetStatsAsync(7)).ReturnsAsync(new TestSetStatsDto());
    var page = new IndexModel(generator.Object, jobs.Object, backgroundQueue.Object, courses.Object, courseAccess.Object, new Mock<ILogger<IndexModel>>().Object)
    {
        PageContext = new PageContext { HttpContext = new DefaultHttpContext() }
    };

    var result = await page.OnGetAsync();

    result.Should().BeOfType<PageResult>();
    page.CourseId.Should().Be(7);
    page.Courses.Should().HaveCount(2);
    generator.Verify(s => s.GetStatsAsync(7), Times.Once);
  }

  [Fact]
  public async Task PreviewPageHandler_ShouldReturnPagedQaPairs()
  {
    var generator = new Mock<ITestSetGeneratorService>();
    var jobs = new Mock<ITestSetGenerationJobManager>();
    var backgroundQueue = new Mock<IBackgroundTaskQueue>();
    var courses = new Mock<ICourseService>();
    var courseAccess = new Mock<ICourseAccessService>();

    var resultPage = PagedResult<QAPairDto>.CreateFromPage(
        new[]
        {
            new QAPairDto { Id = 10, CourseId = 1, DocumentChunkId = 99, Question = "What is RAG?", Answer = "Retrieval augmented generation.", CreatedAt = DateTime.UtcNow }
        },
        page: 2,
        pageSize: 10,
        totalItems: 11);

    generator.Setup(s => s.GetAutoGeneratedPreviewAsync(1, 2, 10)).ReturnsAsync(resultPage);
    var page = new IndexModel(generator.Object, jobs.Object, backgroundQueue.Object, courses.Object, courseAccess.Object, new Mock<ILogger<IndexModel>>().Object)
    {
        PageContext = new PageContext { HttpContext = new DefaultHttpContext() }
    };

    var result = await page.OnGetPreviewAsync(courseId: 1, page: 2, pageSize: 10);

    var json = result.Should().BeOfType<JsonResult>().Subject;
    var model = json.Value.Should().BeAssignableTo<PagedResult<QAPairDto>>().Subject;
    model.Page.Should().Be(2);
    model.TotalItems.Should().Be(11);
    model.Items.Should().ContainSingle(q => q.Id == 10);
  }
}
