using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PRN222.BLL.DTOs;
using PRN222.BLL.Services.Interfaces;
using PRN222.Web.Infrastructure;

namespace PRN222.Web.Pages.TestSetGenerator;

[Authorize(Roles = ApplicationRoles.ModelOperations)]
public class IndexModel(
    ITestSetGeneratorService testSetGeneratorService,
    ITestSetGenerationJobManager jobManager,
    IBackgroundTaskQueue backgroundTaskQueue,
    ICourseService courseService,
    ICourseAccessService courseAccessService,
    ILogger<IndexModel> logger) : PageModel
{
    public TestSetStatsDto Stats { get; private set; } = null!;
    public IReadOnlyList<CourseDto> Courses { get; private set; } = [];
    public int CourseId { get; private set; }

    public async Task<IActionResult> OnGetAsync(int? courseId = null)
    {
        var courses = (await GetVisibleCoursesAsync()).ToList();
        var selectedCourseId = courseId ?? courses.FirstOrDefault()?.Id ?? 0;
        if (selectedCourseId > 0 && !await CanAccessCourseAsync(selectedCourseId))
        {
            return Forbid();
        }

        Stats = await testSetGeneratorService.GetStatsAsync(selectedCourseId);
        Courses = courses;
        CourseId = selectedCourseId;
        return Page();
    }

    public async Task<IActionResult> OnPostGenerateAsync(int courseId = 1, int questionsPerChunk = 2, int maxChunks = 25)
    {
        if (!await CanAccessCourseAsync(courseId))
        {
            return Forbid();
        }

        if (!jobManager.TryStart(courseId, out var token))
        {
            Response.StatusCode = StatusCodes.Status409Conflict;
            return new JsonResult(new { success = false, message = "Dang co job sinh test set cho mon hoc nay." });
        }

        await backgroundTaskQueue.QueueAsync(async (serviceProvider, cancellationToken) =>
        {
            try
            {
                var generator = serviceProvider.GetRequiredService<ITestSetGeneratorService>();
                var jobs = serviceProvider.GetRequiredService<ITestSetGenerationJobManager>();
                await generator.GenerateFromDocumentsAsync(courseId, questionsPerChunk, maxChunks, token, jobs);
            }
            catch (Exception ex)
            {
                jobManager.Fail(courseId, ex.Message);
                logger.LogError(ex, "Background test set generation failed for course {CourseId}.", courseId);
            }
        });

        return new JsonResult(new { success = true, message = "Da bat dau sinh test set. Ban co the o lai trang nay hoac dung job khi can." });
    }

    public async Task<IActionResult> OnPostStopAsync(int courseId = 1)
    {
        if (!await CanAccessCourseAsync(courseId))
        {
            return Forbid();
        }

        var stopped = jobManager.RequestStop(courseId);
        return new JsonResult(new
        {
            success = stopped,
            message = stopped
                ? "Da gui yeu cau dung. Job se dung sau thao tac hien tai."
                : "Khong tim thay job dang chay cho mon hoc nay."
        });
    }

    public async Task<IActionResult> OnPostClearAutoGeneratedAsync(int courseId = 1)
    {
        if (!await CanAccessCourseAsync(courseId))
        {
            return Forbid();
        }

        await testSetGeneratorService.ClearAutoGeneratedAsync(courseId);
        return new JsonResult(new { success = true, message = "Da xoa toan bo Q&A auto-generated cua mon hoc nay." });
    }

    public async Task<IActionResult> OnGetStatsAsync(int courseId = 1)
    {
        if (!await CanAccessCourseAsync(courseId))
        {
            return Forbid();
        }

        var stats = await testSetGeneratorService.GetStatsAsync(courseId);
        return new JsonResult(stats);
    }

    public async Task<IActionResult> OnGetJobStatusAsync(int courseId = 1)
    {
        if (!await CanAccessCourseAsync(courseId))
        {
            return Forbid();
        }

        return new JsonResult(jobManager.GetStatus(courseId));
    }

    public async Task<IActionResult> OnGetPreviewAsync(int courseId = 1, int page = 1, int pageSize = 25)
    {
        if (!await CanAccessCourseAsync(courseId))
        {
            return Forbid();
        }

        var qaPairs = await testSetGeneratorService.GetAutoGeneratedPreviewAsync(courseId, page, pageSize);
        return new JsonResult(qaPairs);
    }

    private bool IsCourseScopedUser() =>
        User?.Identity?.IsAuthenticated == true &&
        !User.IsInRole(ApplicationRoles.Admin) &&
        (User.IsInRole(ApplicationRoles.HeadLecturer) || User.IsInRole(ApplicationRoles.Lecturer));

    private async Task<IEnumerable<CourseDto>> GetVisibleCoursesAsync()
    {
        var courses = (await courseService.GetAllCoursesAsync()).ToList();
        if (!IsCourseScopedUser())
        {
            return courses;
        }

        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        if (string.IsNullOrWhiteSpace(userId))
        {
            return [];
        }

        var assignedCourseIds = await courseAccessService.GetAccessibleStaffCourseIdsAsync(userId);
        return courses.Where(course => assignedCourseIds.Contains(course.Id)).ToList();
    }

    private async Task<bool> CanAccessCourseAsync(int courseId)
    {
        if (!IsCourseScopedUser())
        {
            return true;
        }

        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        if (string.IsNullOrWhiteSpace(userId))
        {
            return false;
        }

        return await courseAccessService.CanStaffAccessCourseAsync(userId, courseId);
    }
}
