namespace PRN222.DAL.Entities;

/// <summary>
/// Represents a single question-answer evaluation result within a benchmark run.
/// Stores RAGAS metrics for quality assessment.
/// </summary>
public class BenchmarkResult
{
    public int Id { get; set; }

    public int BenchmarkRunId { get; set; }

    /// <summary>The question from the test set.</summary>
    public string Question { get; set; } = string.Empty;

    /// <summary>The expected correct answer (ground truth).</summary>
    public string GroundTruth { get; set; } = string.Empty;

    /// <summary>The answer generated by the system.</summary>
    public string GeneratedAnswer { get; set; } = string.Empty;

    /// <summary>RAGAS Faithfulness score (0.0 to 1.0): measures factual consistency.</summary>
    public float Faithfulness { get; set; }

    /// <summary>RAGAS Answer Relevancy score (0.0 to 1.0): measures answer relevance to question.</summary>
    public float AnswerRelevancy { get; set; }

    /// <summary>RAGAS Context Precision score (0.0 to 1.0): measures precision of retrieved context.</summary>
    public float ContextPrecision { get; set; }

    /// <summary>RAGAS Context Recall score (0.0 to 1.0): measures recall of retrieved context.</summary>
    public float ContextRecall { get; set; }

    // Navigation properties
    public BenchmarkRun BenchmarkRun { get; set; } = null!;
}
