namespace PRN222.BLL.DTOs;

public class TestSetStatsDto
{
    public int ManualCount { get; set; }
    public int AutoGeneratedCount { get; set; }
    public int TotalCount { get; set; }
    public int UniqueChunksUsed { get; set; }
    public int TotalChunksAvailable { get; set; }
}
